services:
  app-service:
    build: ./services/app
    ports:
      - "4002:4002"
  user-service:
    build: ./services/users
    ports:
      - "4001:4001"
  orchestrator:
    build: ./orchestrator
    ports:
      - "80:4000"
    environment:
      - APP_URL=http://app-service:4002
      - USER_URL=http://user-service:4001
